# Imagem base leve
FROM python:3.9-slim

WORKDIR /app

# Copia e instala dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o código
COPY . .

# Expõe a porta (documental)
EXPOSE 5000

# Comando de execução
CMD ["python", "app.py"]