# Usa uma imagem leve do Python
FROM python:3.9-slim

# Define diretório de trabalho
WORKDIR /app

# Copia e instala dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o código da aplicação
COPY . .

# Expõe a porta
EXPOSE 5000

# Comando inicial
CMD ["python", "app.py"]